version: '3.9'

networks:
  mlops-network:
    external: true

services:
  minio:
    restart: always
    image: minio/minio:RELEASE.2024-06-22T05-26-45Z
    container_name: minio_20240622
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ':9001' --address ':9000'
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
        - ./minio_data:/data
    networks:
      mlops-network:
        ipv4_address: 172.61.0.2

  mc:
    image: minio/mc:RELEASE.2024-06-20T14-50-54Z
    container_name: mc_20240622
    depends_on:
        - minio
    env_file:
        - .env
    entrypoint: >
        /bin/sh -c "
        /tmp/wait-for-it.sh minio:9000 &&
        /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
        /usr/bin/mc mb minio/mlflow;
        exit 0;
        "
    volumes:
        - ./wait-for-it.sh:/tmp/wait-for-it.sh